<html xmlns:fb="http://ogp.me/ns/fb#">
    <?php
    $product = Mage::registry('current_product');
    if ($product) {
        $width = Mage::getStoreConfig('fsocial/comments/productwidth');
    } else {
        $width = Mage::getStoreConfig('fsocial/comments/cmswidth');
    }
    $commentEnabled = Mage::getStoreConfig('fsocial/comments/commentsmain');

    $noitem = Mage::getStoreConfig('fsocial/comments/noitem');
    $url = $this->helper('core/url')->getCurrentUrl();
    ?>


    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=213087342100033";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <?php if ($commentEnabled) { ?>
        <div id="comment">
            <div class="fb-comments" data-href="<?php echo $url; ?>" data-num-posts="<?php echo $noitem; ?>" data-width="<?php echo $width; ?>"></div>
        </div>
    <?php } ?>



