<script src="http://connect.facebook.net/en_US/all.js"></script>
<script>
    FB.init({
        appId  : '<?php echo $this->getApiID() ?>',
        status : true, // check login status
        cookie : true, // enable cookies to allow the server to access the session
        xfbml  : true  // parse XFBML
    });

</script>

<script>
    document.observe('click', function(e){
        var target = e.findElement('a[rel^=facebook-connect]') || e.findElement('button[rel^=facebook-connect]');
        if (target && target.readAttribute('rel')=='facebook-connect') {              
            e.stop();
            try{
                FB.login(function(response) { 
                                            
            if (response.status == 'connected') {
                setLocation('<?php echo $this->getConnectUrl() ?>');
            } 
        }, {scope:'email,read_stream,user_about_me,publish_stream,offline_access'});
			
            }catch(error){}
        }
    });
    
</script>